### ISSUE TITLE
Marriott Hotel Reservation Kanban Board Setup

### ISSUE THREAD

**Issue by Miliyonayalew** [Miliyonayalew/Marriott-Reservation-Backend#15]
# Kanban board setup 
- We are a group of 4 members
      -  @d4nQw3rty 
      - @HansZizold 
      -  @OscarFMdev
      -  @Miliyonayalew 

## Kanban Board
- Frontend Kanban board setup [Frontend](https://github.com/OscarFMdev/Marriott-Reservation-Frontend/projects/1)
- Backend Kanban board setup [Backend](https://github.com/Miliyonayalew/Marriott-Reservation-Backend/projects/1)

### Frontend
![image](https://user-images.githubusercontent.com/35680940/220982383-42733377-ac3b-4de9-97ed-728ce7e16e2d.png)
![image](https://user-images.githubusercontent.com/35680940/221006026-9efb2f72-5aa4-49ea-adf9-a10b7a6307a6.png)

### Backend
![image](https://user-images.githubusercontent.com/35680940/220982924-4eaff323-8eac-447e-b924-0c5573898dcc.png)

![image](https://user-images.githubusercontent.com/35680940/220982832-8ae6c165-04cd-4afe-8c9a-0d7f57ca9da0.png)

**Comment by vichuge** [comment]
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Suggested changes
_Check the comments under the review._

- It looks like you assign work for only 2 members of the team, but you're 4, please try to have everybody have assignments on the project. At the same time, remember, any of the members should have a close number of points each one (with no more or equal to 5 points for diff).
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/20563252/220987176-6daf8e2c-68d2-4b9c-8588-a7396958347c.png">


You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Miliyonayalew** [comment]
Hey, @vichuge Thanks for the review, we assigned 2 members on the front-end and 2 members on  the back-end can you check it please

**Comment by OscarFMdev** [comment]
# Dear code reviewer, 
we decided to split the project (and the kanban) with the front-end and back-end parts, 2 members are assigned in the front-end and 2 members are in the backend:
## Front-end:
@d4nQw3rty 
@OscarFMdev
 
## Backend:
@Miliyonayalew 
@HansZizold

**Comment by Meltrust** [comment]
Hi @OscarFMdev,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All members have been assigned tasks✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
